<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>

    <!-- Empêche la console noire -->
    <Win32Resource />

    <!-- Icône de l'exécutable -->
    <ApplicationIcon>MediaMonitor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Copie l'icône dans le dossier de sortie -->
    <Content Include="MediaMonitor.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>

