<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\MediaMonitor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\MediaMonitor.ico" CopyToOutputDirectory="Always" />
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="MailKit" Version="4.16.0" />
  </ItemGroup>

  <!-- Référence vers MediaMonitor.Core -->
  <ItemGroup>
    <ProjectReference Include="..\MediaMonitor\MediaMonitor.Core\MediaMonitor.Core.csproj" />
  </ItemGroup>
</Project>



