<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\MediaMonitor.ico</ApplicationIcon>
  </PropertyGroup>

  <!-- Inclusion forcée des ressources -->
  <ItemGroup>
    <!-- Icône -->
    <Content Include="Assets\MediaMonitor.ico" CopyToOutputDirectory="Always" />

    <!-- Dossier Languages (JSON) -->
    <Content Include="Languages\**\*.json" CopyToOutputDirectory="Always" />

    <!-- Autres ressources éventuelles -->
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
  </ItemGroup>
</Project>



