<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\MediaMonitor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaMonitor.Core\MediaMonitor.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Resource Include="Resources\Icons\icon_image.png" />
    <Resource Include="Resources\Icons\icon_video.png" />
    <Resource Include="Resources\Icons\icon_audio.png" />
    <Resource Include="Resources\Icons\icon_serie.png" />
  </ItemGroup>

</Project>

