<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="MailKit" Version="4.16.0" />

      <Content Include="Languages\**\*.json" CopyToOutputDirectory="Always" />
      <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />

      <PackageReference Include="WindowsAPICodePack" Version="8.0.9" />
      <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <!-- Obligatoire pour WPF -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
  </ItemGroup>

  <!-- Référence locale à TagLibSharp.dll -->
  <ItemGroup>
    <Reference Include="TagLibSharp">
      <HintPath>Libs\TagLibSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- ⭐ COPIE AUTOMATIQUE DU DOSSIER FFMPEG ⭐ -->
  <ItemGroup>
    <Content Include="ffmpeg\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>

