<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <ApplicationIcon>Assets\RomMonitor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MediaMonitor\MediaMonitor.Core\MediaMonitor.Core.csproj" />
    <ProjectReference Include="..\..\MCEMonitor.Languages\MCEMonitor.Languages.csproj" />
  </ItemGroup>

  <!-- Assets (icône application) -->
  <ItemGroup>
    <Content Include="Assets\RomMonitor.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- ?? Images et icônes embarquées dans l'assembly (WPF Resource) -->
  <ItemGroup>
    <Resource Include="Resources\Icons\*.png" />
    <Resource Include="Resources\Images\*.png" />
  </ItemGroup>

</Project>